name: Deploy EC2 Instance with NGINX User Data

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2 Instance with NGINX
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-053b0d53c279acc90 \  # Ubuntu AMI
            --instance-type t3.micro \
            --key-name macbook \
            --security-groups default \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=test}]' \
            --user-data file://nginx-user-data.sh \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Wait for EC2 to be ready
        run: |
          aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID

      - name: Get Public IP
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Verify Instance Access with ubuntu user
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/macbook.pem ubuntu@$PUBLIC_IP 'echo "EC2 Instance is accessible!"'

      - name: Verify NGINX Installation
        run: |
          curl http://$PUBLIC_IP
